### ISSUE TITLE
Signature verification does not work

### ISSUE THREAD

**Issue by solokot** [1024mb/APK-Info#3]
Does not start or is not detected java.exe
OS Windows 10 x64
The path is specified in user_config.ini (and is missing in %path%)
Tools\apksigner.jar is present and runs from the command line
The original Enyby/APK-Info in this configuration works
![java](https://github.com/1024mb/APK-Info/assets/25316928/40ddd949-dd80-46ef-8827-af18dbdd3c50)

**Comment by 1024mb** [comment]
Hey, sorry for taking so long. What error do you get? I've tried this and it's working on my end.

EDIT: OK, found the problem, should be working now.
